title: Bayes Book
description: First chapter the book written by LambdaClass
theme: jekyll-theme-tactile
kramdown:
    math_engine: mathjax
defaults:
    - scope:
        path: ""
      values:
        layout: default
