title: Data Science in Julia for Hackers 
 description:  Chapters of the book written by LambdaClass
theme: jekyll-theme-tactile
kramdown:
    math_engine: null
defaults:
    - scope:
        path: ""
      values:
        layout: default
