title: Bayes Book
description: First chapter of the book written by LambdaClass
theme: jekyll-theme-tactile
plugins:
    - jekyll-katex
defaults:
    - scope:
        path: ""
      values:
        layout: default
